site_name: Thomas Tu M.S. Thesis Proposal

use_directory_urls: true

plugins:
  - git-revision-date-localized

markdown_extensions:
  - footnotes
  - admonition

theme:
  name: 'gitbook'
  custom_dir: themes/gitbook
