site_name: Thomas Tu M.S. Thesis Proposal

use_directory_urls: true

plugins:
  - git-revision-date-localized
  - bibtex:
      bib_file: "references.bib"
      cite_style: "pandoc"

markdown_extensions:
  - footnotes
  - admonition

theme:
  name: 'gitbook'
  custom_dir: themes/gitbook